env:
  global:
    - CC_TEST_REPORTER_ID=b741b9c10232b4a3fc3e48cc03e24298c8b7adaa85da8c470c17646b572eab1f
rvm:
  - 2.6.3
  - 2.1.9
  - 1.9.3
language: ruby
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
